// module.js
export function themes() {
	return [
		{ label: 'Default', value: 'default' },
		{ label: '3024-day', value: '3024-day' },
		{ label: '3024-night', value: '3024-night' },
		{ label: 'Abcdef', value: 'abcdef' },
		{ label: 'Ambiance', value: 'ambiance' },
		{ label: 'Ambiance Moblie', value: 'ambiance-mobile' },
		{ label: 'Base16-dark', value: 'base16-dark' },
		{ label: 'Base16-light', value: 'base16-light' },
		{ label: 'Bespin', value: 'bespin' },
		{ label: 'Blackboard', value: 'blackboard' },
		{ label: 'Cobalt', value: 'cobalt' },
		{ label: 'Colorforth', value: 'colorforth' },
		{ label: 'Darcula', value: 'darcula' },
		{ label: 'Dracula', value: 'dracula' },
		{ label: 'Duotone-dark', value: 'duotone-dark' },
		{ label: 'Duotone-light', value: 'duotone-light' },
		{ label: 'Eclipse', value: 'eclipse' },
		{ label: 'Elegant', value: 'elegant' },
		{ label: 'Erlang-dark', value: 'erlang-dark' },
		{ label: 'Gruvbox-dark', value: 'gruvbox-dark' },
		{ label: 'Hopscotch', value: 'hopscotch' },
		{ label: 'Icecoder', value: 'icecoder' },
		{ label: 'Idea', value: 'idea' },
		{ label: 'Isotope', value: 'isotope' },
		{ label: 'Lesser-dark', value: 'lesser-dark' },
		{ label: 'Liquibyte', value: 'liquibyte' },
		{ label: 'Lucario', value: 'lucario' },
		{ label: 'Material', value: 'material' },
		{ label: 'Mbo', value: 'mbo' },
		{ label: 'Mdn-like', value: 'mdn-like' },
		{ label: 'Midnight', value: 'midnight' },
		{ label: 'Monokai', value: 'monokai' },
		{ label: 'Neat', value: 'neat' },
		{ label: 'Neo', value: 'neo' },
		{ label: 'Night', value: 'night' },
		{ label: 'Oceanic-next', value: 'oceanic-next' },
		{ label: 'Panda-syntax', value: 'panda-syntax' },
		{ label: 'Paraiso-dark', value: 'paraiso-dark' },
		{ label: 'Paraiso-light', value: 'paraiso-light' },
		{ label: 'Pastel-on-dark', value: 'pastel-on-dark' },
		{ label: 'Railscasts', value: 'railscasts' },
		{ label: 'Reactjs.org Doc Theme', value: 'react' },
		{ label: 'Rubyblue', value: 'rubyblue' },
		{ label: 'Seti', value: 'seti' },
		{ label: 'Shadowfox', value: 'shadowfox' },
		{ label: 'Solarized', value: 'solarized' },
		{ label: 'The-matrix', value: 'the-matrix' },
		{ label: 'Tomorrow-night-bright', value: 'tomorrow-night-bright' },
		{ label: 'Tomorrow-night-eighties', value: 'tomorrow-night-eighties' },
		{ label: 'Ttcn', value: 'ttcn' },
		{ label: 'Twilight', value: 'twilight' },
		{ label: 'Vibrant-ink', value: 'vibrant-ink' },
		{ label: 'Xq-dark', value: 'xq-dark' },
		{ label: 'Xq-light', value: 'xq-light' },
		{ label: 'Yeti', value: 'yeti' },
		{ label: 'Zenburn', value: 'zenburn' },
	];
}
